using UnityEngine;

public class DoorAnimationController : MonoBehaviour
{
    public Animator doorAnimator;
    public AudioSource doorSound;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player") || other.CompareTag("Guard"))
        {
            // Cambia la condici贸n a true para reproducir la animaci贸n de apertura.
            doorAnimator.SetBool("character_nearby", true);
            doorSound.Play();
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player") || other.CompareTag("Guard"))
        {
            // Cambia la condici贸n a false para reproducir la animaci贸n de cierre.
            doorAnimator.SetBool("character_nearby", false);
            doorSound.Play();
        }
    }
}
